// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TunaPiano.Migrations
{
    [DbContext(typeof(TunaPianoDbContext))]
    [Migration("20240305021452_Update")]
    partial class Update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenreSong", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("integer");

                    b.Property<int>("SongsId")
                        .HasColumnType("integer");

                    b.HasKey("GenresId", "SongsId");

                    b.HasIndex("SongsId");

                    b.ToTable("GenreSong");
                });

            modelBuilder.Entity("TunaPiano.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 40,
                            Bio = "first fave",
                            Name = "No Doubt"
                        },
                        new
                        {
                            Id = 2,
                            Age = 40,
                            Bio = "stole my sister's tape",
                            Name = "Weezer"
                        },
                        new
                        {
                            Id = 3,
                            Age = 40,
                            Bio = "one album wonder",
                            Name = "Lauryn Hill"
                        },
                        new
                        {
                            Id = 4,
                            Age = 80,
                            Bio = "actually a diety",
                            Name = "Stevie Wonder"
                        },
                        new
                        {
                            Id = 5,
                            Age = 50,
                            Bio = "witch store vibes",
                            Name = "Tori Amos"
                        },
                        new
                        {
                            Id = 6,
                            Age = 70,
                            Bio = "former James Brown impersonator",
                            Name = "Charles Bradley"
                        },
                        new
                        {
                            Id = 7,
                            Age = 35,
                            Bio = "cool dude",
                            Name = "Kendrick Lamar"
                        });
                });

            modelBuilder.Entity("TunaPiano.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Rock"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hip-Hop"
                        },
                        new
                        {
                            Id = 3,
                            Description = "R&B"
                        });
                });

            modelBuilder.Entity("TunaPiano.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Album = "Tragic Kingdom",
                            ArtistId = 1,
                            Length = 4,
                            Title = "Sunday Morning"
                        },
                        new
                        {
                            Id = 2,
                            Album = "Tragic Kingdom",
                            ArtistId = 1,
                            Length = 3,
                            Title = "Just a Girl"
                        },
                        new
                        {
                            Id = 3,
                            Album = "Blue Album",
                            ArtistId = 2,
                            Length = 5,
                            Title = "My Name is Jonas"
                        },
                        new
                        {
                            Id = 4,
                            Album = "The Miseducation of Lauryn Hill",
                            ArtistId = 3,
                            Length = 4,
                            Title = "That Thing"
                        },
                        new
                        {
                            Id = 5,
                            Album = "Fulfillingness' First Finale",
                            ArtistId = 4,
                            Length = 5,
                            Title = "They Won't Go When I Go"
                        },
                        new
                        {
                            Id = 6,
                            Album = "Innervisions",
                            ArtistId = 4,
                            Length = 6,
                            Title = "Higher Ground"
                        },
                        new
                        {
                            Id = 7,
                            Album = "Under The Pink",
                            ArtistId = 5,
                            Length = 4,
                            Title = "Cornflake Girl"
                        },
                        new
                        {
                            Id = 8,
                            Album = "No Time For Dreaming",
                            ArtistId = 6,
                            Length = 6,
                            Title = "Lovin' You Baby"
                        },
                        new
                        {
                            Id = 9,
                            Album = "DAMN",
                            ArtistId = 7,
                            Length = 4,
                            Title = "HUMBLE"
                        });
                });

            modelBuilder.Entity("GenreSong", b =>
                {
                    b.HasOne("TunaPiano.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TunaPiano.Models.Song", null)
                        .WithMany()
                        .HasForeignKey("SongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
